Repository WomenWhoGoTokyo/codelab, pull requests merged in 2019-10, with the labels that each got.

#25 Create gocon-2019-autumn-setup
  docs/claat.bash
  docs/gocon-2019-autumn-setup/codelab.json
  docs/gocon-2019-autumn-setup/img/ddf22819b00ffc1a.png
  docs/gocon-2019-autumn-setup/index.html
  docs/index.md
Labels: review

#26 名前の後ろの不要な文字を削除
  docs/index.md
Labels: review

#27 Update cloud shell content
  docs/google-cloud-shell-go/codelab.json
  docs/google-cloud-shell-go/index.html
Labels: in review

#29 upgrade GAE Go to 1.12
  guestbook/.gcloudignore
  guestbook/app.yaml
  guestbook/go.mod
  guestbook/go.sum
  guestbook/index.go
  guestbook/init.go
  guestbook/message.go
  guestbook/post.go
  guestbook/web/main.go
Labels: in review

#30 起動処理を修正
  guestbook/web/main.go
Labels: bug, in review

#32 エンティティの種類（kind）にホスト名を使う
  guestbook/index.go
  guestbook/post.go
Labels: enhancement, in review

#31 Update guestbook codelabs
  docs/google-app-engine-go/codelab.json
  docs/google-app-engine-go/img/1a06f41e46b518ac.png
  docs/google-app-engine-go/img/1b66cf38edf66aaa.png
  docs/google-app-engine-go/img/1d4b9b4b879795b6.png
  docs/google-app-engine-go/img/2134149d242cc260.png
  docs/google-app-engine-go/img/2173982353ccb66e.png
  docs/google-app-engine-go/img/295ea5061777f58.png
  docs/google-app-engine-go/img/2c1b064a698500e9.png
  docs/google-app-engine-go/img/2f4686aea10b14d0.png
  docs/google-app-engine-go/img/32c8037317d68918.png
  docs/google-app-engine-go/img/3b51d206e16a03b.png
  docs/google-app-engine-go/img/479cd32fa947790a.png
  docs/google-app-engine-go/img/4ecc293852dd9e25.png
  docs/google-app-engine-go/img/69250d15abb07e76.png
  docs/google-app-engine-go/img/74bf77b7acf7d2c8.png
  docs/google-app-engine-go/img/8db170257761f568.png
  docs/google-app-engine-go/img/92978e968f2534f2.png
  docs/google-app-engine-go/img/9d1a3eb9485dc94.png
  docs/google-app-engine-go/img/b1b5e2ddba9ea253.png
  docs/google-app-engine-go/img/b30687eeae641446.png
  docs/google-app-engine-go/img/cddcf9f7002d1c5c.png
  docs/google-app-engine-go/img/d6cf1462b8e5891a.png
  docs/google-app-engine-go/img/deba4b7824c236e2.png
  docs/google-app-engine-go/img/e12c5a0676e7a2fd.png
  docs/google-app-engine-go/img/e1ba81a3733790fe.png
  docs/google-app-engine-go/img/efb6a61818c03859.png
  docs/google-app-engine-go/img/f6b544613bc3bb3f.png
  docs/google-app-engine-go/img/fa64bdf84f943298.png
  docs/google-app-engine-go/index.html
Labels: in review, v2
